import { supabaseAdmin } from '../../core/supabase/server-client.js';
import { PaginationInput, toRange } from '../../core/http/pagination.js';
import { assertKnownTable, fieldsByTable } from '../../generated/catalog.js';
const SYSTEM_COLUMNS = new Set(['id','tenant_id','created_at','updated_at','deleted_at','created_by','updated_by','deleted_by']);
function allowedWriteColumns(table: string) { return new Set((fieldsByTable[table] ?? []).map((f) => f.name).filter((name) => !SYSTEM_COLUMNS.has(name))); }
export async function listRows(table: string, tenantId: string, pagination: PaginationInput) { assertKnownTable(table); const { from, to } = toRange(pagination); let query = supabaseAdmin.from(table).select('*', { count: 'exact' }).eq('tenant_id', tenantId).is('deleted_at', null).range(from, to); if (pagination.search) { const col = (fieldsByTable[table] ?? []).find((f) => ['nome','nome_completo','titulo','descricao','razao_social','email'].includes(f.name))?.name; if (col) query = query.ilike(col, `%${pagination.search}%`); } const { data, error, count } = await query; if (error) throw error; return { data, count, page: pagination.page, pageSize: pagination.pageSize }; }
export async function getRow(table: string, tenantId: string, id: string) { assertKnownTable(table); const { data, error } = await supabaseAdmin.from(table).select('*').eq('tenant_id', tenantId).eq('id', id).is('deleted_at', null).single(); if (error) throw error; return data; }
export async function createRow(table: string, tenantId: string, input: Record<string, unknown>, userId: string) { assertKnownTable(table); const allowed = allowedWriteColumns(table); const payload = Object.fromEntries(Object.entries(input).filter(([key]) => allowed.has(key))); const { data, error } = await supabaseAdmin.from(table).insert({ ...payload, tenant_id: tenantId, created_by: userId, updated_by: userId }).select().single(); if (error) throw error; return data; }
export async function updateRow(table: string, tenantId: string, id: string, input: Record<string, unknown>, userId: string) { assertKnownTable(table); const allowed = allowedWriteColumns(table); const payload = Object.fromEntries(Object.entries(input).filter(([key]) => allowed.has(key))); const { data, error } = await supabaseAdmin.from(table).update({ ...payload, updated_by: userId, updated_at: new Date().toISOString() }).eq('tenant_id', tenantId).eq('id', id).is('deleted_at', null).select().single(); if (error) throw error; return data; }
export async function softDeleteRow(table: string, tenantId: string, id: string, userId: string) { assertKnownTable(table); const { error } = await supabaseAdmin.from(table).update({ status: 'EXCLUIDO_LOGICO', deleted_at: new Date().toISOString(), deleted_by: userId }).eq('tenant_id', tenantId).eq('id', id).is('deleted_at', null); if (error) throw error; }
